package com.vilniuscoding.hotel;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.vilniuscoding.hotel.MainApp;

import static org.junit.Assert.*;

public class MainAppTest {
    @Test public void testSomeLibraryMethod() {
        MainApp classUnderTest = new MainApp();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
